imports:
    - { resource: parameters.yml }
    - { resource: parameters_general.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: twig_globals.yml }

parameters:
    locale: app.locale

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
framework:
    #esi: ~
    validation: 
        enable_annotations: true
    serializer:
        enable_annotations: true
    translator:
        fallbacks: 
            - '%locale%'
    default_locale: '%app.locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            uuid_binary: AppBundle\Database\UUIDType
            string_sensitive: AppBundle\Database\StringSensitiveType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: AppBundle\Database\NamingStrategy
        auto_mapping: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Client\Client
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType
            validation_groups: ['App', 'AppRegistration', 'Default']
    profile:
        form:
            type: AppBundle\Form\ProfileType
            validation_groups: ['App', 'AppProfile', 'Default']
    change_password:
        form:
            validation_groups: ['AppChangePassword', 'Default']

knp_doctrine_behaviors:
    translatable: true
