parameters:
    copyright: 2018
    company_name: PHP Symfony Electronics Store
    contact_phone: +1 888 553 8899
    contact_mail: someone@phpsymfonyelectronicsstore.com
    default_locale: fr_CA
    locale: fr_CA
    supported_locales: fr_CA|en_CA|en_US