security:
    encoders:
        AppBundle\Entity\Client\Client:
            algorithm: plaintext

    providers:
        user_database:
            entity:
                class: AppBundle\Entity\Client\Client
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_database
            logout_on_user_change: true
            form_login:
                username_parameter: username
                password_parameter: password
                default_target_path: list_products
                login_path: login
                check_path: login
            logout:
                path: logout
                target: list_products
