# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    ClientInterface\Fixer:
        factory: 
            - '@AppBundle\Service\Factory\ClientAPIFactory'
            - __invoke
        arguments: 
            - '%api.fixer.uri%'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        public: true
        tags: 
            - 'controller.service_arguments'

    AppBundle\Command\:
        resource: '../../src/AppBundle/Command/*'
        public: true
        tags:
            - 'console.command'

    AppBundle\Command\UpdateMoneyConvertersCommand:
        arguments:
            $client: '@ClientInterface\Fixer'
        tags:
            - { name: 'console.command', command: 'app:update-currencies' }

    AppBundle\Database\NamingStrategy:
        public: true

    AppBundle\Form\AddressType:
        arguments:
            - '@request_stack'
        tags:
            - { name: form.type }

    AppBundle\Form\RegistrationType:
        tags:
            - { name: form.type, alias: app_user_registration }

    AppBundle\Repository\ItemRepository:
        factory: 
            - '@Doctrine\ORM\EntityManagerInterface'
            - getRepository
        arguments:
            - 'AppBundle\Entity\Item'


    AppBundle\Service\:
        resource: '../../src/AppBundle/Service/*'

    AppBundle\Service\Factory\ClientAPIFactory:
        arguments: 
            - '%api.param.timeout%'

    AppBundle\Subscriber\:
        resource: '../../src/AppBundle/Subscriber/*'

    AppBundle\Subscriber\LocaleSubscriber:
        arguments:
            $default: '%app.locale%'
            $accepted: '%app.locales%'

    AppBundle\Twig\:
        resource: '../../src/AppBundle/Twig/*'
        tags: 
            - 'twig.extension'

    AppBundle\Twig\ProductExtension:
        arguments: 
            - '%app.routes.memory%'