twig:
    globals:
        copyright: '%app.copyright%'
        companyname: '%app.company.name%'
        contactphone: '%app.contact.phone%'
        contactmail: '%app.contact.mail%'
        locales: '%app.locales%'
        locale: '%app.locale%'
        route_memory: '%app.routes.memory%'

